[package]
name = "bee_solver"
description = "Solver for the NYT Spelling Bee"
authors = ["Jacob Elder"]
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
regex = "1.11.1"
zstd = "0.13.3"

[[bin]]
name = "bee_solver"
path = "src/bin/bee_solver.rs"